services:

  pos-sales-service:
    build:
      context: ./apps/pos-sales-service
      dockerfile: Dockerfile
    container_name: smartstore-pos-sales-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI_SALES: ${MONGODB_URI_SALES}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3002/api/pos/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  pos-catalog-service:
    build:
      context: ./apps/pos-catalog-service
      dockerfile: Dockerfile
    container_name: smartstore-pos-catalog-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGODB_URI_CATALOG: ${MONGODB_URI_CATALOG}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3003/api/catalog/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  pos-service:
    build:
      context: ./apps/pos-service
      dockerfile: Dockerfile
    container_name: smartstore-pos-service
    restart: unless-stopped
    depends_on:
      pos-sales-service:
        condition: service_healthy
      pos-catalog-service:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI_POS: ${MONGODB_URI_POS}
      CORS_ORIGIN: "*"
      CATALOG_SERVICE_URL: http://pos-catalog-service:3003/api
      SALES_SERVICE_URL: http://pos-sales-service:3002/api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3001/api/pos/dashboard"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  pos-web:
    build:
      context: ./apps/pos-web
      dockerfile: Dockerfile
    container_name: smartstore-pos-web
    restart: unless-stopped
    depends_on:
      pos-service:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      API_BASE_URL: http://pos-service:3001/api

